name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      
      - name: build docker image
        run: |
          docker build -t pawz.hu .
      
      - name: stop and remove old container
        run: |
          docker stop pawz.hu || true
          docker rm pawz.hu || true
      
      - name: run docker container
        run: |
          docker run -d --name pawz.hu -p 3000:3000 pawz.hu
      
      - name: clean up
        run: |
          docker system prune -f